//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/users/
Content-Type: application/json

{
  "id": "// EN USER ID"
}

###

// SKAPA USER
POST http://localhost:3000/users/add
Content-Type: application/json

{
  "name": "Sven Svensson",
  "email": "sven@mail.com",
  "password": "123"
}

###

// LOGGA IN USER
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "// EN USER EMAIL",
  "password": "// EN USER EMAIL"
}

###

//
// API ENDPOINTS PRODUKTER
//

// HÄMTA ALLA PRODUKTER

# @name getProducts
GET http://localhost:3000/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/products/64185fadd456fbef64af6c73

###

// SKAPA PRODUKT
POST http://localhost:3000/products/add
Content-Type: application/json

{
  "name": "Metallica t-shirt",
  "description": "Svart t-shirt med Metallica tryck",
  "price": 50, 
  "lager": 5
}

###

//
// API ENDPOINTS ORDERS
//

// SKAPA ORDER FÖR EN SPECIFIK USER // PRODUCTS ÄR EN ARRAY MOTSVARANDE INNEHÅLLET I KUNDVAGN
# POST http://localhost:3000/products/orders/add
# Content-Type: application/json

# {
#   "user": "{{getUsers.response.body.$[0].id}}",
#       "products": [
#     {
#       "productId": "// ID PÅ EN PRODUKT",
#       "quantity": 1
#     },
#     {
#       "productId": "// ID PÅ EN PRODUKT",
#       "quantity": 2
#     }
#   ]
# }

###


// HÄMTA ALLA ORDERS
GET http://localhost:3000/products/orders/all/

###